package net.ronm19.infernummod.entity.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class EmberHundAnimations {


public static final Animation EMBER_HUND_WALKING = Animation.Builder.create(1f).looping()

        .addBoneAnimation("leg4",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.9f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, -0.8f, 2.1f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -0.9f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0.1f, -0.25f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.9f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg4",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("tail",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.48f, 0.07f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.45f, -0.9f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("tail",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(12f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg1",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.7f, 0.3f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.3f, 2.1f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -0.7f, 0.3f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.09f, -1.06f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.7f, 0.3f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg1",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg2",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.6f, 0.4f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.07f, -1.38f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -0.6f, 0.4f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, 0.5f, 1.3f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.6f, 0.4f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg2",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg3",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -0.8f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.9f, -1.3f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -0.8f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.11f, 1.36f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.8f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg3",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createRotationalVector(12f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR))).build();
public static final Animation EMBER_HUND_IDLE = Animation.Builder.create(1f).looping()
        .addBoneAnimation("tail",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0.8f, 0.1f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createTranslationalVector(0f, -0.7f, -0.5f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("tail",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.25f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.75f, AnimationHelper.createRotationalVector(-15f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR))).build();
public static final Animation EMBER_HUND_ATTACK = Animation.Builder.create(1.25f).looping()
        .addBoneAnimation("head",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5416766f, AnimationHelper.createTranslationalVector(0f, -1.5f, -0.5f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("head",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(0.5416766f, AnimationHelper.createRotationalVector(17.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR))).build();
public static final Animation EMBER_HUND_SIT = Animation.Builder.create(1f)
        .addBoneAnimation("head",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 2f, 0.9f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("body",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(-16f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg1",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(-63f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg2",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0.3f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg2",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(-68.88f, -0.13f, 0.67f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg3",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 1.4f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg3",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(90f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg4",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 1.1f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("leg4",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(88.5f, 0f, 0f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("tail",
                new Transformation(Transformation.Targets.TRANSLATE,
                        new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -4.2f, -0.8f),
                                Transformation.Interpolations.LINEAR)))
        .addBoneAnimation("tail",
                new Transformation(Transformation.Targets.ROTATE,
                        new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                Transformation.Interpolations.LINEAR),
                        new Keyframe(1f, AnimationHelper.createRotationalVector(-19f, 0f, 0f),
                                Transformation.Interpolations.LINEAR))).build();
}